### ISSUE TITLE
Any way to set my backend local ip as endpoint url?

### ISSUE THREAD

**Issue by AgustinJimenez** [bytefury/crater-mobile#1]
![Screen Shot 2019-12-01 at 17 08 12](https://user-images.githubusercontent.com/21246906/69919613-8854e300-145d-11ea-9849-55557ef2cd84.png)

**Comment by ysfbsf** [comment]
You have to make your endpoint public with a dynamic domain name. You can use No-IP for that.

**Comment by Bgosse1** [comment]
Maybe try [ngrok](https://ngrok.com/)
