### ISSUE TITLE
Authentication failing HTTP 405

### ISSUE THREAD

**Issue by barf** [bytefury/crater-mobile#10]
Recently authentication began failing on mobile, but works OK on a browser such as Firefox.

I have reproduced this on two installs now, version 3.3.0 updated via the GUI. Hosted on OpenBSD/Apache2/PHP7.

The mobile app was installed on Android via the Google Play store - version 4.0.0.

Is this client version not backwards-compatible with 3.3.0?

**Comment by mohitpanjwani** [comment]
4.0.0 update is pretty huge and it's not backwards compatible. 

The previous backend API was pretty messy and we revamped basically everything so it wasn't possible to keep supporting the old versions. 

All the future versions of Crater will be backwards compatible of-course,

**Comment by barf** [comment]
thank you for your work! good to know!
