### ISSUE TITLE
How to mark an invoice as completed?

### ISSUE THREAD

**Issue by SteveEdson** [bytefury/crater-mobile#23]
Back when I was using V3.1 I could mark an invoice as completed. Now, even if I record a payment for the full amount of the invoice, it still shows as due. I can't see anywhere in the UI to change this.

Is this a bug? I'm on 4.1.0

Thanks

**Comment by calumshep** [comment]
Can confirm this bug exists on the iOS version too. Nice work figuring it out @SteveEdson
