### ISSUE TITLE
Missing updates?

### ISSUE THREAD

**Issue by feuzeu** [bytefury/crater-mobile#5]
Hi,
Thanks for this wonderful app.

I've installed the mobile app on my android device from the play store, and the latest version is the 3.0.0, published on february 1st.
However, the last commit on this repository was made on december, and the version is stil set to 2.0.2.

Are there any updates on the mobile app that are not committed on this repository?

Regards

**Comment by mohitpanjwani** [comment]
Hey @feuzeu. 

We've pushed the remaining changes. 

Thanks for the heads up.

**Comment by feuzeu** [comment]
Thanks @mohitpanjwani
