### ISSUE TITLE
Unable to launch Expo

### ISSUE THREAD

**Issue by LarryBarker** [bytefury/crater-mobile#7]
Hello, I've just cloned the repo and am receiving an error that the Expo Client requires a different SDK version (I have tried both a simulator on my mac, and my iphone):

![image](https://user-images.githubusercontent.com/28734844/89143694-157e9900-d511-11ea-8865-eb46746692f5.png)

Is it safe to upgrade the Expo SDK for my copy?

**Comment by mohitpanjwani** [comment]
Hey, we've pushed a small change that should fix this issue. 

Basically we upgraded expo to the latest 37 version. 

Please pull the changes and let me if you encounter any other issues.
